site_name: Riggedbooks
theme:
    name: readthedocs
nav:
    
    - 主页: index.md
    
    - 安装: install.cn.md
    
    - 快速入门: quickstart.cn.md
    
    - 书本变换: transform.cn.md
    
    - 参数解释: parameters.cn.md
    
    - 材质替换: changematerials.cn.md
  
    - 动画调节: animations.cn.md
  
    - 页数定制: custom page number.cn.md

    - 常见问题: questions.cn.md

    - 不能做的: cannotdo.cn.md

    - 版本更新: changelogs.cn.md

extra_css:
    - css/extra.css

markdown_extensions:
    - admonition
    - attr_list




        


    
        

