site_name: Riggedbooks
theme:
    name: readthedocs
nav:
    
    - 主页: index.md
    
    - 安装: install.md
    
    - 快速入门: quickstart.md
    
    - 书本变换: transform.md
    
    - 参数解释: parameters.md
    
    - 材质替换: changematerials.md
  
    - 动画调节: animations.md
  
    - 页数定制: custom page number.md

    - 常见问题: questions.md

    - 不能做的: cannotdo.md

    - 版本更新: changelogs.md

extra_css:
    - css/extra.css

markdown_extensions:
    - admonition
    - attr_list




        


    
        

